from __future__ import annotations

from pathlib import Path

import torch

from transformer_nuggets.export_autograd_triton import (
    Specialization,
    export_autograd_triton,
    load_exported_module,
)


def tiny_mlp(x, w1, w2, *, activation="relu"):
    hidden = x @ w1
    if activation == "relu":
        hidden = torch.relu(hidden)
    elif activation == "gelu":
        hidden = torch.nn.functional.gelu(hidden)
    else:
        raise ValueError(f"unsupported activation: {activation}")
    return hidden @ w2


def main():
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required for this example")

    output_path = Path("agent_space/generated_tiny_mlp.py")
    x = torch.randn(4, 8, device="cuda", requires_grad=True)
    w1 = torch.randn(8, 16, device="cuda", requires_grad=True)
    w2 = torch.randn(16, 3, device="cuda", requires_grad=True)

    exported = export_autograd_triton(
        tiny_mlp,
        specializations=[
            Specialization(
                args=(x, w1, w2),
                kwargs={"activation": "relu"},
                name="relu_4x8_8x16_16x3",
            )
        ],
        out=output_path,
        source_backend="clean_triton",
        max_autotune=True,
    )

    generated = load_exported_module(output_path)
    eager_x = x.detach().clone().requires_grad_()
    eager_w1 = w1.detach().clone().requires_grad_()
    eager_w2 = w2.detach().clone().requires_grad_()
    compiled_x = x.detach().clone().requires_grad_()
    compiled_w1 = w1.detach().clone().requires_grad_()
    compiled_w2 = w2.detach().clone().requires_grad_()

    eager = tiny_mlp(eager_x, eager_w1, eager_w2, activation="relu")
    compiled = generated.tiny_mlp_compiled(
        compiled_x,
        compiled_w1,
        compiled_w2,
        activation="relu",
    )
    torch.testing.assert_close(compiled, eager)

    eager.sum().backward()
    compiled.sum().backward()
    torch.testing.assert_close(compiled_x.grad, eager_x.grad)
    torch.testing.assert_close(compiled_w1.grad, eager_w1.grad)
    torch.testing.assert_close(compiled_w2.grad, eager_w2.grad)

    print(f"exported_name: {exported.exported_name}")
    print(f"specializations: {exported.specializations}")
    artifact_dir = output_path.with_name(f"{output_path.stem}_artifacts")
    print(f"generated file: {output_path}")
    print(f"generated bytes: {output_path.stat().st_size}")
    print(f"artifact dir: {artifact_dir}")
    for artifact_path in sorted(artifact_dir.glob("*.py")):
        print(f"  {artifact_path.name}: {artifact_path.stat().st_size} bytes")


if __name__ == "__main__":
    main()
